import getpass
import sys
import telnetlib

HOST = "198.18.1.45"
user = raw_input("Enter your telnet username: ")
password = getpass.getpass()

tn = telnetlib.Telnet(HOST)

tn.read_until("Username: ")
tn.write(user + "\n")
if password:
    tn.read_until("Password: ")
    tn.write(password + "\n")

tn.write("conf t\n")
tn.write("vrf red\n")
tn.write("address-family ipv4 uni\n")
tn.write("import route-target 45:45\n")
tn.write("export route-target 45:45\n")
tn.write("vrf blue\n")
tn.write("address-family ipv4 uni\n")
tn.write("import route-target 450:450\n")
tn.write("export route-target 450:450\n")
tn.write("exit\n")
tn.write("exit\n")
tn.write("int lo5\n")
tn.write("no ip address\n")
tn.write("vrf red\n")
tn.write("ipv4 address 5.5.5.5 255.255.255.255\n")
tn.write("no shut\n")
tn.write("int lo15\n")
tn.write("no ip address\n")
tn.write("vrf blue\n")
tn.write("ipv4 address 15.15.15.15 255.255.255.255\n")
tn.write("no shut\n")
tn.write("int lo50\n")
tn.write("no ip address\n")
tn.write("vrf red\n")
tn.write("ipv4 address 50.50.50.50 255.255.255.255\n")
tn.write("no shut\n")
tn.write("int lo55\n")
tn.write("vrf red\n")
tn.write("no ip address\n")
tn.write("ipv4 address 55.55.55.55 255.255.255.255\n")
tn.write("no shut\n")
tn.write("int lo155\n")
tn.write("no ip address\n")
tn.write("vrf blue\n")
tn.write("ipv4 address 155.155.155.155 255.255.255.255\n")
tn.write("no shut\n")
tn.write("int lo150\n")
tn.write("no ip address\n")
tn.write("vrf blue\n")
tn.write("ipv4 address 150.150.150.150 255.255.255.255\n")
tn.write("no shut\n")
tn.write("exit\n")
tn.write("router bgp 65000\n")
tn.write("neighbor-group RR-services-group\n")
tn.write("address-family vpnv4 unicast\n")
tn.write("route-policy SET_COLOR_IN in\n")
tn.write("vrf red\n")
tn.write("rd 45:45\n")
tn.write("address-family ipv4 unicast\n")
tn.write("redis connected\n")
tn.write("vrf blue\n")
tn.write("rd 450:450\n")
tn.write("address-family ipv4 unicast\n")
tn.write("redis connected\n")
tn.write("extcommunity-set opaque 4\n")
tn.write("4 end-set\n")
tn.write("extcommunity-set opaque 14\n")
tn.write("14 end-set\n")
tn.write("extcommunity-set opaque 40\n")
tn.write("40 end-set\n")
tn.write("extcommunity-set opaque 44\n")
tn.write("44 end-set\n")
tn.write("extcommunity-set opaque 140\n")
tn.write("140 end-set\n")
tn.write("extcommunity-set opaque 144\n")
tn.write("144 end-set\n")
tn.write("route-policy SET_COLOR_IN\n")
tn.write("if rd in (45:45) and destination in (4.4.4.4/32) then\n")
tn.write("set extcommunity color 4\n")
tn.write("elseif rd in (45:45) and destination in (40.40.40.40/32) then\n")
tn.write("set extcommunity color 4\n")
tn.write("elseif rd in (45:45) then\n")
tn.write("set extcommunity color 44\n")
tn.write("elseif rd in (450:450) and destination in (14.14.14.14/32) then\n")
tn.write("set extcommunity color 14\n")
tn.write("elseif rd in (450:450) and destination in (140.140.140.140/32) then\n")
tn.write("set extcommunity color 140\n")
tn.write("elseif rd in (450:450) then\n")
tn.write("set extcommunity color 144\n")
tn.write("else pass endif\n")
tn.write("end-policy\n")
tn.write("mpls traff\n")
tn.write("int g0/0/0/0\n")
tn.write("admin-weight 1\n")
tn.write("int g0/0/0/1\n")
tn.write("admin-weight 2\n")
tn.write("commit\n")
tn.write("end\n")
tn.write("show vrf all\n")
tn.write("exit\n")

print tn.read_all()